[bugfix] patch sensu-client (#7)
* patch sensu-client

because sensu-client cannot find installed plugins

* test stdout as well

* use thresholds that never fail

* another patch for sensu-transport

sensu-client raises the following exception and fails to reconnect

{"timestamp":"2017-07-12T01:50:45.063738+0000","level":"info","message":"configuring
sensu spawn","settings":{"limit":12}}
{"timestamp":"2017-07-12T01:50:45.146030+0000","level":"warn","message":"transport
connection error","reason":"tcp connection lost"}
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-transport-7.0.2/lib/sensu/transport/rabbitmq.rb:210:in
`block in setup_connection': undefined method `[]' for nil:NilClass
(NoMethodError)

* check only '/' partition

and ignore other funky file systems, such as debug fs on some platforms

* remove hard-coded path to the target

* workaround an issue in the jenkins environment

* create symlinks to plug-in's binaries

also, fix issues in the previous commits by moving some tests to correct
places.

* QA

* refine regexp

* remove block to workaround an issue in ubuntu box

TASK [ansible-role-sensu-client : Create symlinks]
***************************** fatal: [localhost]: FAILED! => {"failed": true,
"msg": "'dict object' has no attribute 'stdout_lines'"}

the latest, 0.3.0, does not cause the error.

* add another condition

it should not have been there but ansible in ubuntu 1604 still complains

* bugfix: quote condition

when containing quotes, it must be quoted

* workaround a possible bug in ansible

`when` condition should be evaluated before expanding the valiable in
`with_items`, and ansible should not raise error, IMO.

* workaround an issue in jenkins

* update the patch

https://github.com/reallyenglish/ansible-role-sensu-server/pull/5/commits/7de8d955314b3dc2a068b51e695e3cbf3e5b0ffa

* update the test as well